# Generated by Django 3.0.6 on 2020-06-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='poster',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
